### ISSUE TITLE
Error/Spam

### ISSUE THREAD

**Issue by alfari24** [brblacky/lavalink-list#33]
after i added my lavalink, i get like this filling up all my logs and consoles. i've changed the lavalink version but same thing.

https://note.alfari.id/o/r/54

**Comment by brblacky** [comment]
It is issue with your lavalink server 

Other lavalink connection is stable!

**Comment by alfari24** [comment]
its issue with your web lavalink status, doing spaming. do you see other people say same issue with me ?.
do you see how much lavalink server people give are offline now because this. @brblacky 

[resource-blob.txt](https://github.com/brblacky/lavalink-list/files/13941179/resource-blob.txt)

i give 2 node with diff port,
and at your website only show node-2. and only that get effect. 
when i change the port all fine.

my server can handle 200 connection with clearly, in other port.


I have changed all the lavalink ports, because your web lavalink status is scary, making so much spam.

**Comment by alfari24** [comment]
![image](https://github.com/brblacky/lavalink-list/assets/56450870/67869e7c-7fc7-49b6-bc6a-aaacdaf67867)

**Comment by brblacky** [comment]
Only issue with your lavalink other lavalink are don't reconnecting!

The Lavalink server status API connects only once during restart or start. It remains stable thereafter, without any functionality for node spamming.
